#!/usr/bin/env python3
# Converts the "Next" logo art PNGs to src/res/next_art.h: palette index
# images (0 = transparent) and their palettes, one per variant. With
# --boot PREFIX, the first image also goes to the bootloader's boot screen:
# PREFIX.h has its size, PREFIX.inc its palette (padded to 8 colors) and
# pixels (4 bits per pixel, left pixel in the high nibble).
#   next2c.py [--boot PREFIX] OUT.h A.png [B.png ...]
import sys
from PIL import Image

def gba(c):
    r, g, b = c[:3]
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)

args = sys.argv[1:]
boot = None
if args[0] == "--boot":
    boot, args = args[1], args[2:]
out = ["// Generated by res/next/next2c.py, do not edit.", "#include <stdint.h>", ""]
for n, path in enumerate(args[1:]):
    im = Image.open(path).convert("RGBA")
    pal = []
    rows = []
    for y in range(im.height):
        row = []
        for x in range(im.width):
            p = im.getpixel((x, y))
            if p[3] < 128:
                row.append(0)
                continue
            c = gba(p)
            if c not in pal:
                pal.append(c)
            row.append(pal.index(c) + 1)
        rows.append(row)
    assert len(pal) <= 32, (path, len(pal))
    out.append("static const uint8_t next_art%d[%d][%d] = {" % (n, im.height, im.width))
    for row in rows:
        out.append("  {" + ",".join(str(v) for v in row) + "},")
    out.append("};")
    out.append("__attribute__((unused)) static const uint16_t next_art%d_pal[%d] = {%s};" % (n, len(pal), ",".join("0x%04x" % c for c in pal)))
    out.append("")
    if boot and n == 0:
        assert len(pal) <= 8 and im.width % 2 == 0
        open(boot + ".h", "w").write(
            "// Generated by res/next/next2c.py, do not edit.\n"
            "#define BOOT_NEXT_W %d\n#define BOOT_NEXT_H %d\n" % (im.width, im.height))
        b = ["@ Generated by res/next/next2c.py, do not edit.",
             "boot_next_pal:", "  .hword " + ",".join("0x%04x" % c for c in pal + [0] * (8 - len(pal))),
             "boot_next_art:"]
        for row in rows:
            b.append("  .byte " + ",".join("0x%x%x" % (row[x], row[x + 1]) for x in range(0, len(row), 2)))
        b.append("  .balign 4")
        open(boot + ".inc", "w").write("\n".join(b) + "\n")
open(args[0], "w").write("\n".join(out))
